# This is a basic configuration that performs verifying DKIM signatures.
#
# For more advanced options, see opendkim.conf(5):
# http://www.opendkim.org/opendkim.conf.5.html

UserID                  opendkim:opendkim
BaseDirectory           /run/opendkim

Socket local:/run/opendkim/opendkim.sock
UMask 000
PidFile /run/opendkim/opendkim.pid

Syslog                  Yes
SyslogSuccess           Yes

Mode                    v
Canonicalization        relaxed/simple
