UserID                  opendkim:opendkim
BaseDirectory           /run/opendkim

Socket local:/run/opendkim/opendkim.sock
UMask 000
PidFile /run/opendkim/opendkim.pid

Syslog                  Yes
SyslogSuccess           Yes

Mode                    sv
Canonicalization        relaxed/simple

# Sign for example.com with key in /etc/mail/dkim.key using
# selector 'default' (e.g. default._domainkey.test.com)
Domain			test.com
KeyFile		  /var/db/dkim/default.private
Selector		default
